title: "Dare Afolabi – Data Analytics Portfolio"
description: "Portfolio of dashboards and data analysis projects built with Google Sheets and Excel."
keywords: Google Sheets & Excel Dashboard | Data Analyst Portfolio
theme: slate
